#!/bin/sh

# copia o arquivo contendo variáveis de ambiente
cp .env.example .env

# gera uma nova chave de aplicação
./worksapce key:generate

# builda os containers
docker compose up -d

# instala as dependências do composer
./composer install

# roda as migrations
./worksapce migrate
